var BezierPath = require('../utils/bezier_path');

module.exports = {
  alif1: require('./abjad/alif_i'),
  baa: [],
  taa: [],
  thaa: [],
  jiim: [],
  h1aa: require('./abjad/h1aa'),
  khaa: [],
  daal: [],
  dhaal: [],
  raa: [],
  zayn: [],
  siin: [],
  shiin: [],
  Saad: [],
  Daad: [],
  Taa: [],
  Dhaa: [],
  a3yn: [],
  ghayn: [],
  faa: [],
  qaaf: [],
  kaaf: [],
  laam: [],
  miim: [],
  nuun: [],
  haa1: require('./abjad/haa_i'),
  waw: [],
  yaa: [],
  taamrbTa: [],
  lamalf23: require('./abjad/lamalf_m_f'),
  alfmqSra: [],
  hamza: [],
  fatHa: [],
  Damma: [],
  ksra: []
};
