var BezierPath = require('../utils/bezier_path');

module.exports = {
  alif1: require('./abjad/alif_i'),
  baa: [],
  taa: [],
  thaa: [],
  jiim: [],
  h1aa: require('./abjad/h1aa'),
  khaa: [],
  daal: [],
  dhaal: [],
  raa: [],
  zayn: [],
  siin: require('./abjad/siin'),
  siin1: require('./abjad/siin_i'),
  shiin: [],
  Saad: [],
  Daad: [],
  Taa: [],
  Dhaa: [],
  a3yn: [],
  ghayn: [],
  faa: [],
  qaaf: [],
  kaaf: [],
  laam: [],
  miim: [],
  nun: require('./abjad/nun'),
  haa1: require('./abjad/haa_i'),
  haa2: require('./abjad/haa_m'),
  waaw: require('./abjad/waaw'),
  yaa: [],
  taamrbTa: [],
  lamalf23: require('./abjad/lamalf_m_f'),
  alfmqSra: [],
  hamza: [],
  fatHa: require('./abjad/fatHa'),
  Damma: [],
  ksra: [],
  tanwiin: require('./abjad/tanwiin'),
  space: require('./abjad/space')
};
